Controllers films users
iozimniy/java-filmorate pull request #1
Opened 2024-09-29 20:01 UTC by iozimniy

2024-09-30 05:10 UTC, EugeneLenkevich requested changes
Привет, Мария! Спасибо за PR.

Моментик с валидацией отметил, посмотри, пожалуйста, комментарии

2024-09-30 05:10 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +        if (film.getName() == null || film.getName().isBlank()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2024-09-30 05:10 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +        if (film.getName() != null && film.getName().isBlank()) {
Кстати, а не получится ли тут обойтись аннотациями `"@NotNull`, `"@NotBlank` и пр, для проверки емейла у нас аннотация стоит, в контроллере `@Valid` есть, то есть валидация должна работать и так, аннотациями, без ручных проверок?

Вижу только тут проблемы будут с тестами на валидаторы, в случае аннотаций ошибки падать будут в контроллерах. И тут я боюсь наврать в подсказать то чего не требуется именно в этом задании, спроси, пожалуйста, у наставника как лучше быть на данном этапе и нужны ли тут тесты валидации вообще. Но, по идее, null  и на пустые строки проверяются через аннотации, ручные проверки тут выглядят лишними :)

2024-09-30 05:10 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/validations/FilmValidationTest.java
> +    public void createFilm() {
Только private наверно :)

2024-09-30 05:10 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/validations/FilmValidationTest.java
> +    FilmController filmController = new FilmController();
А контроллер в этом тесте точно нужен, вроде нигде не используется

2024-09-30 05:10 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/validations/FilmValidationTest.java
> +    public void createFilmDescription200ValidationException() {
Кстати, про именование тестовых методов. Есть два подхода
- старый, test + имя метода, то есть  testCreateFilmDescription
- новый, с should + имя метода, то есть как то так shouldCreateFilmSucessfully

https://stackoverflow.com/questions/33354801/proper-naming-convention-for-junit-test-methods

![image](https://github.com/user-attachments/assets/e3a75bcc-91c3-4c45-9efc-2e549f98df27)

2024-10-02 16:40 UTC, iozimniy commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +        if (film.getName() != null && film.getName().isBlank()) {
> Кстати, а не получится ли тут обойтись аннотациями `"@NotNull`, `"@NotBlank` и пр, для проверки емейла у нас аннотация стоит, в контроллере `@Valid` есть, то есть валидация должна работать и так, аннотациями, без ручных проверок?
> 
> Вижу только тут проблемы будут с тестами на валидаторы, в случае аннотаций ошибки падать будут в контроллерах. И тут я боюсь наврать в подсказать то чего не требуется именно в этом задании, спроси, пожалуйста, у наставника как лучше быть на данном этапе и нужны ли тут тесты валидации вообще. Но, по идее, null и на пустые строки проверяются через аннотации, ручные проверки тут выглядят лишними :)

Звучит разумно, однако, тут есть проблемка с тем, что фактически null быть может, но не при создании нового пользователя или фильма. Например, если с фронта нам приходит PUT-запрос, и в нём только поля, в которых были изменения, а не все поля. Тогда будет падать на валидации при создании экземпляра класса User/Film в контроллере, тогда как нам наоборот нужно получить объект только с изменёнными полями.
По полю id - отдельная тема. В запросе на создание он должен быть null, в запросе на изменение он, наоборот, должен быть не null.

2024-10-02 16:50 UTC, iozimniy commented on src/test/java/ru/yandex/practicum/filmorate/validations/FilmValidationTest.java
> +    FilmController filmController = new FilmController();
> А контроллер в этом тесте точно нужен, вроде нигде не используется

Используется, когда проверяем id в PUT-запросе. У нас хранение реализовано в контроллерах, и, соответственно, проверить, что у нас фильм для изменения по id не находится, мы можем через создание объекта контроллера.

Тест и проверка на id в методе update в контроллере. 
![image](https://github.com/user-attachments/assets/880fe781-6675-4864-a5e6-69065bbf8376)
![image](https://github.com/user-attachments/assets/95f5ffee-f9e1-4fdb-9fb0-e3724b2a9108)

2024-10-02 16:58 UTC, iozimniy commented on src/test/java/ru/yandex/practicum/filmorate/validations/FilmValidationTest.java
> +    public void createFilmDescription200ValidationException() {
Переименовать на новый вариант? Он кажется более удобным.
На курсе по автотестам в Практикуме предлагали вариант: имя метода + входные параметры + ожидаемый результат. По привычке делаю так, хоть это и довольно громоздко, но мне не принципиально, если вам кажется такой вариант нечитаемым.))

2024-10-02 17:37 UTC, iozimniy commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +        if (film.getName() != null && film.getName().isBlank()) {
Реализовала для поля name класса File аннотацию @NotBlank. Она не ломает логику PUT-запроса.

2024-10-02 18:02 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +        if (film.getName() != null && film.getName().isBlank()) {
Ладно ок, пусть так будет, главное мы умеем в аннотации

2024-10-02 18:05 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/validations/FilmValidationTest.java
> +    public void createFilmDescription200ValidationException() {
О, пусть так будет, не критично совершенно, но на заметку лучше это все взять, все равно надо смотреть по тому как на конкретном проекте приянто

2024-10-02 18:07 UTC, EugeneLenkevich approved these changes
Главное тут разобраться с основными принципами, вроде все понятно, все гут, тогда поехали дальше :)

2024-10-02 18:35 UTC, merged