Add friends likes
iozimniy/java-filmorate pull request #2
Opened 2024-10-13 21:52 UTC by iozimniy

2024-10-14 09:06 UTC, EugeneLenkevich requested changes
Привет, Катя! Спасибо за PR.

Все хорошо, единственное, давай проверим распределение ответственности по слоям.  У каждого слоя есть свои обязанности, если простыми словами то вот так
- контроллеры маршрутизируют сами запросы на наши сервисы
- сервисы оперируют понятиями предметной области, в них и содержится вся бизнес-логика 
- хранилище же занимается вопросами хранения, фильтрации и выборки данных

Посмотри, пожалуйста, код на предмет того, как обязанности распределены по слоям.

2024-10-14 09:06 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //private FilmStorage filmStorage;
Ну и почистить сразу этот закомментированный код, зачем его тут оставлять, в нем смысла больше нет в этом месте :)

2024-10-14 09:06 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!(filmStorage.isContains(film.getId()))) {
Пусть метод называется просто contains, проще же, один лишь глагол без лишних слов :)

2024-10-14 09:06 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikes().add(userId);
film.getLikes().add(userId);

Детали реализации вытаскиваем на уровень сервиса, а давай сделаем примерно такой метод
storage.addLikes(film, userId)
Тогда у нас внутренняя реализация хранилища будет скрыта и мы ее в будущем сможем менять без изменений в сервисах :)

2024-10-14 09:06 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(filmLikesComparator.reversed())
А вот тут в сервис мы вытаскиваем все данные из хранилища и сортируем их, а если поменяется тип хранилища то у нас может кончится память :)

Вообще, выборка и сортировка - это обязанности хранилища, потому лучше опять таки спрятать это выражение в метод хранилища. Так же, потом, нам проще будет делать оптимизации хранения данных, прозрачно для сервисов

2024-10-14 09:06 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return otherUser.getFriends().stream()
Опять так, фильтрация просится в метод хранилища

2024-10-14 09:06 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        log.info("Создан новый пользователь: {}", user);
Выглядит будь то два сообщения лога про одно и то же :)

2024-10-21 18:41 UTC, iozimniy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(filmLikesComparator.reversed())
Оставила тут компоратор, остальное перенесла в метод хранилища. Вероятно, это не правильно, но тогда придётся под каждую сортировку хранилища писать отдельный метод для хранилища. Не уверена в решении, в общем.

2024-10-22 08:54 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(filmLikesComparator.reversed())
Ну, в общем случае подход с компаратором не будет работать. Допустим у нас есть таблица заказов и мы хотим видеть последние в табличке со страничками по N записей. Мы не будем выгружать всю таблицу, мы ее отсортируем на уровне БД по дате и выберем только первые N записей. Если это делать в сервисе компаратором то надо будет вытаскивать всю таблицу, не особо эффективно плюс она может вообще не влезть в ОЗУ :)

Обычно каким то образом динамически добавляют сортировку в сам sql-запрос, в сроку.
Далее мы увидим как это фреймворки делают, пока просто имей в виду что этот вариант спорный :)

2024-10-22 08:59 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-10-25 19:28 UTC, merged