Add database
iozimniy/java-filmorate pull request #3
Opened 2024-11-10 19:05 UTC by iozimniy

2024-11-11 16:23 UTC, EugeneLenkevich requested changes
Привет, Мария! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

В первую очередь хочется избавится от запросов в циклах, все до конца можно не править, это муторно вручную делать а нам надо, в первую очередь, чтобы было понимание. Так что хватит нескольких однотипных. Вот, потом со Spring Data, запросы станет писать легче, там да, будет до конца делать :)

https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

2024-11-11 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +            throw new InternalServerException("Не удалось обновить данные");
InternalServerException

Давай все таки не такое исключение тут кидать, оно не информативно и походит на 500-ый http-код ошибки, но мы то находимся на уровне взаимодействия с базой данных, пусть тут будет какое то исключение (проверяемое), указывающее на ошибку данных, с более информативным именем :)

2024-11-11 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +                    .map(obj -> genreStorage.getById(obj.getId()).get())
Запрос в БД - дорогая операция, их лучше минимизировать, а тут же в запросе идут запросы, это не особо эффективно особенно если у нас будет много записей в БД.
По сути дела мы делаем запрос
select * from table where id = :id

можно заменить на

select * from table where id in (:ids)

где ids - список идентификаторов :)

2024-11-11 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmGenreService.java
> +            filmGenreStorage.create(film.getId(), genre.getId());
В идеале бы, конечно, эти запросы в цикле тоже превратить в один. В принципе можно же объединить все в один insert into-запрос

2024-11-11 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +    boolean isContainsId(Long id);
Можно назвать просто contains, а то как то много всего, плюс офр. ошибка.. в общем лучше попроще назвать :)

2024-11-11 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +                if (!genreStorage.isContainsId(genre.getId())) {
Опять таки в цикле запросы

2024-11-12 11:12 UTC, iozimniy commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +                if (!genreStorage.isContainsId(genre.getId())) {
Стрим мне чекстайл не пропустил.)))

2024-11-12 19:52 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validations/FilmValidation.java
> +                if (!genreStorage.isContainsId(genre.getId())) {
Ну там стрим не помог бы, там бы все оформить в один запрос

2024-11-12 19:56 UTC, EugeneLenkevich approved these changes
Смотрю в целом все понятно, супер, отдельно хочется похвалить за активное использование стримов, но с ними надо аккуратней, иногда может читаемость страдать :)

2024-11-13 08:32 UTC, merged